### ISSUE TITLE
Sui token deployment not work

### ISSUE THREAD

**Issue by parley0x** [dsrvlabs/wds-code-remix#41]
seem there is an error on sui when i try to deploy the token, there is getting so many error. it is still work or no? because in 2023 im trying its work but for now its not.

**Comment by altpd13** [comment]
Hello parley0x. Could you tell me what move package you are trying to deploy and show me the error code please?

**Comment by parley0x** [comment]
its work fine for now, thanks

Pada Sel, 24 Sep 2024 pukul 14.49 kairoski03 ***@***.***>
menulis:
